#!/bin/bash

set -e

export SCRIPT_DIR="$(dirname $0)"
export PROJECT_ROOT="$(readlink -f "$SCRIPT_DIR/../..")"
export TARGET_RELEASE_DIR="$PROJECT_ROOT/target/release"
export ARTIFACTS_DIR="$(readlink -f "$SCRIPT_DIR/../artifacts")"

finish() {
    cd "$OLD_PWD"
}

trap finish EXIT

cd "$SCRIPT_DIR"

rm -rf "$ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR"

cp "$TARGET_RELEASE_DIR/zenohd" "$ARTIFACTS_DIR/"
cp "$TARGET_RELEASE_DIR/libzenoh_plugin_"*.so "$ARTIFACTS_DIR/"
