#!/bin/bash

SCRIPT_DIR="$(dirname $0)"
DOCKER_DIR="$(readlink -f "$SCRIPT_DIR/..")"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.yml}"

echo "Use compose file: $COMPOSE_FILE"

docker compose -f "$DOCKER_DIR/$COMPOSE_FILE" down
