#!/bin/bash

SCRIPT_DIR="$(dirname $0)"
DOCKER_DIR="$(readlink -f "$SCRIPT_DIR/..")"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.yml}"

TEST_NET_ADMIN="${TEST_NET_ADMIN:-test-net-admin}"

ADDRESS=$(docker inspect $COMPOSE_PROJECT_NAME-orchestrator-1 | jq -r ".[0].NetworkSettings.Networks.[\"${COMPOSE_PROJECT_NAME}_admin\"].IPAddress")

"$TEST_NET_ADMIN" --orchestrator "http://$ADDRESS:50051" ap --policies "$DOCKER_DIR/$COMPOSE_FILE"
