[package]
rust-version = { workspace = true }
name = "zenoh-link-bt-gatt"
version = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
description = "Internal crate for zenoh."

[dependencies]
async-trait = { workspace = true }
bluer = { workspace = true, features = ["bluetoothd", "id"] }
futures = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["io-std", "macros", "net", "rt-multi-thread", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
uuid = { workspace = true, default-features = true }
zenoh-core = { workspace = true }
zenoh-link-commons = { workspace = true }
zenoh-protocol = { workspace = true }
zenoh-sync = { workspace = true }
zenoh-result = { workspace = true }
zenoh-runtime = { workspace = true }