[package]
rust-version = { workspace = true }
name = "zenoh-link-bt-l2cap-tls"
version = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
description = "Internal crate for zenoh — BLE L2CAP CoC + TLS transport."

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rustls-pki-types = { workspace = true }
tokio = { workspace = true, features = ["io-std", "macros", "net", "rt-multi-thread", "time"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
uuid = { workspace = true, default-features = true }
zenoh-config = { workspace = true }
zenoh-core = { workspace = true }
zenoh-link-commons = { workspace = true, features = ["tls"] }
zenoh-protocol = { workspace = true, default-features = false }
zenoh-result = { workspace = true, default-features = false }
zenoh-runtime = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
bluer = { workspace = true, features = ["bluetoothd", "id", "l2cap"] }
x509-parser = { workspace = true }
